/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inventory.ui;
import com.inventory.ui.LoginFrame;
import javax.swing.UnsupportedLookAndFeelException;
import com.inventory.dao.UserDAO;
import com.inventory.model.User;
/**
 *
 * @author bhaskarjoshi
 */
public class HomeFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeFrame.class.getName());

    /**
     * Creates new form HomeFrame
     * @param role
     */
    public HomeFrame(String role) { // Now it accepts the String from LoginFrame
    initComponents();
    
    // This is the magic line that fixes the "mini window" issue
    this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    
    this.setLocationRelativeTo(null);
    
    // Your existing role-based logic
    if (role.equalsIgnoreCase("User")) {
        btnUser.setVisible(false);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnUser = new javax.swing.JLabel();
        btnCategory = new javax.swing.JLabel();
        btnProduct = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainContent.setPreferredSize(null);
        mainContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(632, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel2.setText("Order");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 48, 29, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        btnUser.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnUser.setText("Manage Users");
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 58, 29, 0);
        jPanel1.add(btnUser, gridBagConstraints);

        btnCategory.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnCategory.setText("Manage Category");
        btnCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoryMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 44, 29, 0);
        jPanel1.add(btnCategory, gridBagConstraints);

        btnProduct.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnProduct.setText("Manage Product");
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 45, 29, 0);
        jPanel1.add(btnProduct, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setText("View Order");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 45, 29, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 52, 29, 51);
        jPanel1.add(btnLogout, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Customers");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 47, 29, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        // 1. Create the panel
        UserManagementPanel userPanel = new UserManagementPanel();
    
        // 2. Clear the current dashboard view
        mainContent.removeAll();
    
        // 3. Add the user panel to the main window
        mainContent.add(userPanel);
    
        // 4. Refresh the window to show changes
        mainContent.revalidate();
        mainContent.repaint();
    }//GEN-LAST:event_btnUserMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int a = javax.swing.JOptionPane.showConfirmDialog(this, "Do you want to logout?", "Select", javax.swing.JOptionPane.YES_NO_OPTION);
        if (a == 0) {
        this.dispose(); // Closes the HomeFrame
    
    // 1. Declare the variable 'lf' and assign the new LoginFrame to it
    LoginFrame lf = new LoginFrame(); 
    
    // 2. Now you can use 'lf' to maximize the window
    lf.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); 
    
    // 3. Make it visible
    lf.setVisible(true);
    }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoryMouseClicked
        // TODO add your handling code here:
        mainContent.removeAll();
    // Ensure the mainContent uses BorderLayout so the new panel fills it
    mainContent.setLayout(new java.awt.BorderLayout()); 
    
    CategoryManagementPanel catPanel = new CategoryManagementPanel();
    // Adding to CENTER forces it to stretch to the edges
    mainContent.add(catPanel, java.awt.BorderLayout.CENTER); 
    
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_btnCategoryMouseClicked

    private void btnProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseClicked
        // TODO add your handling code here:
        // 1. Remove whatever is currently in the center panel
    mainContent.removeAll();
    
    // 2. Set the layout to BorderLayout so the panel stretches to fill the screen
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. Create the Product Management Panel
    ProductManagementPanel productPanel = new ProductManagementPanel();
    
    // 4. Add it to the center
    mainContent.add(productPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh the UI to show the new content
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_btnProductMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        // 1. Clear the current panel being displayed
    mainContent.removeAll();
    
    // 2. Set the layout to BorderLayout so the new panel fills the space
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. Create an instance of your Customer panel
    CustomerManagementPanel customerPanel = new CustomerManagementPanel();
    
    // 4. Add it to the center of your dashboard
    mainContent.add(customerPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh the UI to show the new panel
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        // 1. Clear the current panel
    mainContent.removeAll();
    
    // 2. Set the layout to BorderLayout so it fills the screen
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. Create the ManageOrderPanel instance
    ManageOrderPanel orderPanel = new ManageOrderPanel();
    
    // 4. Add it to the center of your dashboard
    mainContent.add(orderPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh the UI
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        // 1. Clear the current panel content
    mainContent.removeAll();
    
    // 2. Set the layout to BorderLayout so the new panel fills the space
    mainContent.setLayout(new java.awt.BorderLayout());
    
    // 3. Create the ViewOrderPanel instance
    ViewOrderPanel viewPanel = new ViewOrderPanel();
    
    // 4. Add it to the center of your main dashboard area
    mainContent.add(viewPanel, java.awt.BorderLayout.CENTER);
    
    // 5. Refresh the UI to show the new panel
    mainContent.revalidate();
    mainContent.repaint();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeFrame("Admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCategory;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnProduct;
    private javax.swing.JLabel btnUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainContent;
    // End of variables declaration//GEN-END:variables
}
