/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.ui;


import com.inventory.dao.CustomerDAO;

import com.inventory.model.Customer;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.inventory.dao.ProductDAO;
import com.inventory.model.Product; // You'll likely need this too
import com.inventory.dao.ProductDAO;
import com.inventory.dao.OrderDAO;
import com.inventory.model.Order;

/**
 *
 * @author bhaskarjoshi
 */
public class ManageOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderPanel
     */
    public ManageOrderPanel() {
        initComponents();
        ((DefaultTableModel)tblCart.getModel()).setRowCount(0); 
    loadTables();
        loadTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerMobile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnClearCustomer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JTextField();
        btnSaveOrder = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProductPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProductCategory = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtOrderQuantity = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setPreferredSize(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(466, 0));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Selected Customer:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel3.setText("Mobile Number");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Search Customer");

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnClearCustomer.setText("Clear");
        btnClearCustomer.addActionListener(this::btnClearCustomerActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(txtCustomerName)
                        .addComponent(txtCustomerMobile)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(60, 60, 60)
                        .addComponent(btnClearCustomer)))
                .addGap(74, 74, 74))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClearCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCustomerMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(464, 448));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Quantity", "Price", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCart);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setText("Total Amount Rs");

        lblTotalAmount.setEditable(false);

        btnSaveOrder.setText("Save Order Details");
        btnSaveOrder.addActionListener(this::btnSaveOrderActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaveOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalAmount))
                .addGap(27, 27, 27)
                .addComponent(btnSaveOrder)
                .addGap(31, 31, 31)
                .addComponent(btnReset)
                .addGap(29, 29, 29)
                .addComponent(btnClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setMinimumSize(new java.awt.Dimension(355, 100));

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProduct);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Selected Product");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel6.setText("Product Name");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel7.setText("Product Price");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel8.setText("Product Category");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jLabel9.setText("Order Quantity");

        txtOrderQuantity.addActionListener(this::txtOrderQuantityActionPerformed);

        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(btnClear))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnAddToCart, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtOrderQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(18, 18, 18)
                .addComponent(btnAddToCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        int row = tblCustomer.getSelectedRow();
    if (row != -1) {
        int id = (int) tblCustomer.getValueAt(row, 0);
        
        // Find the full customer details from the DAO using the ID
        List<Customer> customers = new CustomerDAO().getAllCustomers();
        for(Customer c : customers) {
            if(c.getCustomerId() == id) {
                txtCustomerName.setText(c.getName());
                txtCustomerMobile.setText(c.getMobile());
                break;
            }
        }
    }
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void loadTables() {
    // 1. Setup Customer Table (ID, Name, Address)
    DefaultTableModel custModel = (DefaultTableModel) tblCustomer.getModel();
    custModel.setRowCount(0); // Clear table first
    
    try {
        List<com.inventory.model.Customer> customers = new com.inventory.dao.CustomerDAO().getAllCustomers();
        for (com.inventory.model.Customer c : customers) {
            custModel.addRow(new Object[]{
                c.getCustomerId(), 
                c.getName(), 
                c.getAddress() // Showing Address as per your requirement
            });
        }
    } catch (Exception e) {
        System.out.println("Error loading customers: " + e.getMessage());
    }

    // 2. Setup Product Table (ID, Name, Price, Quantity)
    DefaultTableModel prodModel = (DefaultTableModel) tblProduct.getModel();
    prodModel.setRowCount(0); // Clear table first
    
    try {
        List<com.inventory.model.Product> products = new com.inventory.dao.ProductDAO().getAllProducts();
        for (com.inventory.model.Product p : products) {
            prodModel.addRow(new Object[]{
                p.getProductId(), 
                p.getName(), 
                p.getPrice(), 
                p.getCurrentQuantity() // Shows current stock
            });
        }
    } catch (Exception e) {
        System.out.println("Error loading products: " + e.getMessage());
    }
}
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchMobile = txtSearch.getText().trim();
    
    if (searchMobile.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a mobile number to search.");
        return;
    }

    boolean found = false;
    List<Customer> customers = new CustomerDAO().getAllCustomers();

    for (Customer c : customers) {
        if (c.getMobile().equals(searchMobile)) {
            // Fill the display fields
            txtCustomerName.setText(c.getName());
            txtCustomerMobile.setText(c.getMobile());
            
            // Highlight the customer in the table for visual confirmation
            for (int i = 0; i < tblCustomer.getRowCount(); i++) {
                if ((int)tblCustomer.getValueAt(i, 0) == c.getCustomerId()) {
                    tblCustomer.setRowSelectionInterval(i, i);
                    break;
                }
            }
            found = true;
            break;
        }
    }

    if (!found) {
        int response = JOptionPane.showConfirmDialog(this, 
            "Customer not found. Would you like to add a new record for " + searchMobile + "?", 
            "Not Found", JOptionPane.YES_NO_OPTION);

        if (response == JOptionPane.YES_OPTION) {
            String name = JOptionPane.showInputDialog(this, "Enter Full Name:");
            if (name != null && !name.isEmpty()) {
                String email = JOptionPane.showInputDialog(this, "Enter Email:");
                String address = JOptionPane.showInputDialog(this, "Enter Address:");

                Customer newCust = new Customer();
                newCust.setName(name);
                newCust.setMobile(searchMobile);
                newCust.setEmail(email);
                newCust.setAddress(address);

                if (new CustomerDAO().addCustomer(newCust)) {
                    loadTables(); // Refresh to show new customer address in table
                    txtCustomerName.setText(name);
                    txtCustomerMobile.setText(searchMobile);
                }
            }
        }
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCustomerActionPerformed
        // TODO add your handling code here:
        // 1. Clear the text fields
    txtSearch.setText("");
    txtCustomerName.setText("");
    txtCustomerMobile.setText("");
    
    // 2. Clear the table selection
    tblCustomer.clearSelection();
    
    // 3. Optional: Reset the focus back to the search field for the next customer
    txtSearch.requestFocus();
    }//GEN-LAST:event_btnClearCustomerActionPerformed

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        // TODO add your handling code here:
        
    // 1. Validation: Check if a customer is selected
    if (txtCustomerName.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a customer first!");
        return; // Stops the rest of the code from running
    }

    // 2. Validation: Check if a product is selected
    if (txtProductName.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a product!");
        return;
    }
    
        String qtyText = txtOrderQuantity.getText().trim();
    int selectedRow = tblProduct.getSelectedRow();

    // 1. Basic Validation
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the table first.");
        return;
    }
    if (qtyText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the quantity.");
        return;
    }

    try {
        int orderQty = Integer.parseInt(qtyText);
        int stockAvailable = Integer.parseInt(tblProduct.getValueAt(selectedRow, 3).toString());
        double price = Double.parseDouble(txtProductPrice.getText());

        // 2. Business Logic Validation
        if (orderQty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.");
            return;
        }
        if (orderQty > stockAvailable) {
            JOptionPane.showMessageDialog(this, "Insufficient stock! Only " + stockAvailable + " available.");
            return;
        }

        // 3. Calculation & Cart Update
        double subtotal = orderQty * price;
        int productId = (int) tblProduct.getValueAt(selectedRow, 0);
        String productName = txtProductName.getText();

        DefaultTableModel cartModel = (DefaultTableModel) tblCart.getModel();
        cartModel.addRow(new Object[]{
            productId,
            productName,
            orderQty,
            price,
            subtotal
        });

        // 4. Update the Grand Total
        updateGrandTotal();
        
        // 5. Reset Product inputs for the next item
        clearProductFields();
        tblProduct.clearSelection();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity. Please enter a whole number.");
    }
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int row = tblProduct.getSelectedRow();
    if (row != -1) {
        try {
            // 1. Safely get the ID using toString() to avoid casting errors
            int selectedId = Integer.parseInt(tblProduct.getValueAt(row, 0).toString());
            
            // 2. Fetch only the specific product details from the DAO
            com.inventory.dao.ProductDAO pDao = new com.inventory.dao.ProductDAO();
            com.inventory.model.Product p = pDao.getProductById(selectedId);

            if (p != null) {
                // --- PART 1: STOCK CHECKS ---
                int stock = p.getCurrentQuantity(); 
                int threshold = p.getMinThreshold(); 

                if (stock <= 0) {
                    JOptionPane.showMessageDialog(this, "OUT OF STOCK! You cannot select " + p.getName());
                    tblProduct.clearSelection();
                    return; 
                }
                
                if (stock <= p.getMinThreshold()) {
                    JOptionPane.showMessageDialog(this, "LOW STOCK ALERT: Only " + stock + " left for " + p.getName(), "Warning", JOptionPane.WARNING_MESSAGE);
                }

                // --- PART 2: EXPIRY CHECKS ---
                if (p.getExpiryDate() != null) {
                    long diff = p.getExpiryDate().getTime() - System.currentTimeMillis();
                    long days = diff / (1000 * 60 * 60 * 24);

                    if (days < 0) {
                        JOptionPane.showMessageDialog(this, "STOP: This product EXPIRED " + Math.abs(days) + " days ago!", "Expired", JOptionPane.ERROR_MESSAGE);
                        tblProduct.clearSelection();
                        return;
                    } else if (days <= 7) {
                        JOptionPane.showMessageDialog(this, "EXPIRY ALERT: " + p.getName() + " expires in " + days + " days!", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                }

                // --- PART 3: UI POPULATION ---
                txtProductName.setText(p.getName());
                txtProductPrice.setText(String.valueOf(p.getPrice()));
                // Ensure your Product model has getCategoryName()
                txtProductCategory.setText(p.getCategoryName()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selection Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_tblProductMouseClicked

    private void updateGrandTotal() {
    double total = 0;
    DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
    
    for (int i = 0; i < model.getRowCount(); i++) {
        try {
            // Get the value and safely convert it to a String then to a Double
            Object value = model.getValueAt(i, 4); 
            if (value != null) {
                total += Double.parseDouble(value.toString());
            }
        } catch (Exception e) {
            System.err.println("Error calculating row " + i + ": " + e.getMessage());
        }
    }
    
    // This works for both JLabel and JTextField
    lblTotalAmount.setText("" + String.format("%.2f", total));
}
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearProductFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtOrderQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderQuantityActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        // 1. Clear text fields
    txtSearch.setText("");
    txtCustomerName.setText("");
    txtCustomerMobile.setText("");
    txtProductName.setText("");
    txtProductPrice.setText("");
    txtProductCategory.setText("");
    txtOrderQuantity.setText("");
    
    // 2. Clear tables and labels
    DefaultTableModel cartModel = (DefaultTableModel) tblCart.getModel();
    cartModel.setRowCount(0);
    lblTotalAmount.setText("");
    
    // 3. Clear selections
    tblCustomer.clearSelection();
    tblProduct.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveOrderActionPerformed
        // TODO add your handling code here:
        // 1. Basic Validation
    if (txtCustomerName.getText().isEmpty() || tblCart.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Please select a customer and add items to the cart!");
        return;
    }

    try {
        // 2. Prepare Order Object
        com.inventory.model.Order order = new com.inventory.model.Order();
        int customerRow = tblCustomer.getSelectedRow();
        int customerId = Integer.parseInt(tblCustomer.getValueAt(customerRow, 0).toString());
        order.setCustomerId(customerId);
        
        // Extract numerical total (e.g., "Total Amount RS: 500.0" -> 500.0)
        String totalText = lblTotalAmount.getText().replaceAll("[^0-9.]", "");
        order.setTotalAmount(Double.parseDouble(totalText));

        // 3. Save Order to Database
        com.inventory.dao.OrderDAO orderDao = new com.inventory.dao.OrderDAO();
        DefaultTableModel cartModel = (DefaultTableModel) tblCart.getModel();
        int generatedOrderId = orderDao.saveOrder(order, cartModel);

        if (generatedOrderId != -1) {
            com.inventory.dao.ProductDAO pDao = new com.inventory.dao.ProductDAO();
            
            for (int i = 0; i < cartModel.getRowCount(); i++) {
                // Get data from the cart table
                int pId = Integer.parseInt(cartModel.getValueAt(i, 0).toString());
                String pName = cartModel.getValueAt(i, 1).toString();
                int qtyToSubtract = Integer.parseInt(cartModel.getValueAt(i, 2).toString());

                // 4. Proactive Threshold Check using your specific variable names
                com.inventory.model.Product p = pDao.getProductById(pId); 
                
                // Using your specific variables: currentQuantity and minThreshold
                int stockAfterSale = p.getCurrentQuantity() - qtyToSubtract;

                if (stockAfterSale <= p.getMinThreshold()) {
                    JOptionPane.showMessageDialog(this, "CRITICAL: " + pName + 
                        " is now at " + stockAfterSale + " units. Please restock immediately!");
                }

                // 5. Update the stock in the database
                pDao.updateStock(pId, qtyToSubtract);
            }

            // 6. Finalize UI
            JOptionPane.showMessageDialog(this, "Order #" + generatedOrderId + " Saved Successfully!");
            generatePDF(generatedOrderId); 
            btnResetActionPerformed(null); 
            loadTables(); 
            
        } else {
            JOptionPane.showMessageDialog(this, "Failed to create Order record in Database.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSaveOrderActionPerformed
    private void clearProductFields() {
    txtProductName.setText("");
    txtProductPrice.setText("");
    txtProductCategory.setText("");
    txtOrderQuantity.setText("");
}
    // Add this method inside your ManageOrderPanel class
private void generatePDF(int orderId) {
    try {
        // 1. Define the folder name within your project
        String folderPath = "generated_pdfs";
        java.io.File folder = new java.io.File(folderPath);
        
        // 2. Create the folder if it doesn't exist
        if (!folder.exists()) {
            folder.mkdir();
        }

        // 3. Set the final file path
        String path = folderPath + "/Order_" + orderId + ".pdf";
        
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream(path));
        doc.open();
        
        // --- PDF Content ---
        doc.add(new com.itextpdf.text.Paragraph("INVENTORY MANAGEMENT SYSTEM - RECEIPT"));
        doc.add(new com.itextpdf.text.Paragraph("Order ID: " + orderId));
        doc.add(new com.itextpdf.text.Paragraph("Date: " + new java.util.Date().toString()));
        doc.add(new com.itextpdf.text.Paragraph("--------------------------------------------------\n\n"));
        
        com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(5);
        table.addCell("ID");
        table.addCell("Name");
        table.addCell("Qty");
        table.addCell("Price");
        table.addCell("Subtotal");

        for (int i = 0; i < tblCart.getRowCount(); i++) {
            table.addCell(tblCart.getValueAt(i, 0).toString());
            table.addCell(tblCart.getValueAt(i, 1).toString());
            table.addCell(tblCart.getValueAt(i, 2).toString());
            table.addCell(tblCart.getValueAt(i, 3).toString());
            table.addCell(tblCart.getValueAt(i, 4).toString());
        }
        
        doc.add(table);
        doc.add(new com.itextpdf.text.Paragraph("\nTotal Amount: " + lblTotalAmount.getText()));
        doc.close();
        
        // 4. Open the PDF from the new project location
        java.awt.Desktop.getDesktop().open(new java.io.File(path));
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "PDF Error: " + e.getMessage());
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearCustomer;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveOrder;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lblTotalAmount;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtCustomerMobile;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtOrderQuantity;
    private javax.swing.JTextField txtProductCategory;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
