/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.ui;

import javax.swing.table.DefaultTableCellRenderer; // Fixes DefaultTableCellRenderer error
import javax.swing.JTable;                       // Fixes JTable error
import javax.swing.JLabel;                       // Required for alignment
import java.awt.Component;                       // Fixes getTableCellRendererComponent return type
import java.awt.Color;                           // Required for the alert colors
import java.util.List;                           // Fixes the 'List' symbol error
import com.inventory.model.Category;             // Required for your Category list
/**
 *
 * @author bhaskarjoshi
 */
public class ProductManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductManagementPanel
     */
    public ProductManagementPanel() {
        initComponents();
    setupTableUI();
    tblProducts.getTableHeader().setFont(new java.awt.Font("STSong", java.awt.Font.BOLD, 18));
        tblProducts.setRowHeight(30);
        tblProducts.setFont(new java.awt.Font("STSong", java.awt.Font.PLAIN, 18));
    setupTableAlerts();    // Customizes look for your Mac screen
    loadCategories();  // Populates the dropdown
    loadTableData();   // Fills the table from DB
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        comboCategory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xtThreshold = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        dateExpiry = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(null);

        tblProducts.setBackground(new java.awt.Color(255, 255, 255));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Price", "Quantity", "Threshold", "Expiry Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducts);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(355, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Name");

        txtName.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Price");

        txtPrice.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Quantity");

        txtQuantity.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N

        comboCategory.setBackground(new java.awt.Color(255, 255, 255));
        comboCategory.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        comboCategory.setForeground(new java.awt.Color(0, 0, 0));
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Category");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Threshold");

        xtThreshold.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("STSong", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Expiry Date");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 0));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        dateExpiry.setBackground(new java.awt.Color(255, 255, 255));
        dateExpiry.setForeground(new java.awt.Color(0, 0, 0));
        dateExpiry.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(xtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xtThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(dateExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnDelete))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1054, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
        com.inventory.model.Product p = new com.inventory.model.Product();
        p.setName(txtName.getText().trim());
        p.setPrice(Double.parseDouble(txtPrice.getText()));
        p.setCurrentQuantity(Integer.parseInt(txtQuantity.getText()));
        p.setMinThreshold(Integer.parseInt(xtThreshold.getText()));
        
        // UPDATED: Get date from JDateChooser (dateExpiry)
        java.util.Date selectedDate = dateExpiry.getDate(); 
        if (selectedDate != null) {
            // Convert java.util.Date to java.sql.Date for the Database
            p.setExpiryDate(new java.sql.Date(selectedDate.getTime()));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an Expiry Date from the calendar!");
            return;
        }

        // Category ID Lookup
        String catName = comboCategory.getSelectedItem().toString();
        int catId = new com.inventory.dao.CategoryDAO().getCategoryIdByName(catName);
        p.setCategoryId(catId);

        if (new com.inventory.dao.ProductDAO().addProduct(p)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Product Added!");
            loadTableData();
            clearFields();
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid input! Price, Quantity, and Threshold must be numeric.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int index = tblProducts.getSelectedRow();
    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a product from the table to update!");
        return;
    }

    try {
        com.inventory.model.Product p = new com.inventory.model.Product();
        p.setProductId((Integer) tblProducts.getValueAt(index, 0)); 
        p.setName(txtName.getText().trim());
        p.setPrice(Double.parseDouble(txtPrice.getText()));
        p.setCurrentQuantity(Integer.parseInt(txtQuantity.getText()));
        p.setMinThreshold(Integer.parseInt(xtThreshold.getText()));
        
        // UPDATED: Get date from JDateChooser (dateExpiry)
        java.util.Date selectedDate = dateExpiry.getDate();
        if (selectedDate != null) {
            p.setExpiryDate(new java.sql.Date(selectedDate.getTime()));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an Expiry Date!");
            return;
        }

        String catName = comboCategory.getSelectedItem().toString();
        p.setCategoryId(new com.inventory.dao.CategoryDAO().getCategoryIdByName(catName));

        if (new com.inventory.dao.ProductDAO().updateProduct(p)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Product Updated successfully!");
            loadTableData();
            clearFields();
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Update failed. Check your data.");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int index = tblProducts.getSelectedRow();
    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a product to delete!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Delete this product?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        int id = (Integer) tblProducts.getValueAt(index, 0);
        if (new com.inventory.dao.ProductDAO().deleteProduct(id)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Product Deleted!");
            loadTableData();
            clearFields();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
        // TODO add your handling code here:
        int index = tblProducts.getSelectedRow();
if (index == -1) return;

// 1. Basic Text Fields
txtName.setText(tblProducts.getValueAt(index, 1).toString());
comboCategory.setSelectedItem(tblProducts.getValueAt(index, 2).toString());
txtPrice.setText(tblProducts.getValueAt(index, 3).toString());
txtQuantity.setText(tblProducts.getValueAt(index, 4).toString());
xtThreshold.setText(tblProducts.getValueAt(index, 5).toString());

// 2. UPDATED: Date Selection Logic for dateExpiry
try {
    // Get the date string from the table (assuming it's in column 6)
    String dateStr = tblProducts.getValueAt(index, 6).toString();
    
    // Convert String "yyyy-MM-dd" to java.util.Date
    java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(dateStr);
    
    // Set the calendar component to this date
    dateExpiry.setDate(date);
} catch (Exception e) {
    // If date is null or unparseable, clear the calendar
    dateExpiry.setDate(null);
}

btnSave.setEnabled(false); // Switch to "Update/Delete" mode
    }//GEN-LAST:event_tblProductsMouseClicked
   
    
    private void setupTableUI() {
        // 1. Get the header object from your JTable
    javax.swing.table.JTableHeader header = tblProducts.getTableHeader();

    // 2. Set the font to STSong, Bold, Size 18
    header.setFont(new java.awt.Font("STSong", java.awt.Font.BOLD, 18));

    // 3. Set the text color (Foreground) to Black
    header.setForeground(java.awt.Color.BLACK);

    // 4. Important: Increase the header height so the larger font isn't cut off
    header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        for (int i = 0; i < tblProducts.getColumnCount(); i++) {
            tblProducts.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        ((DefaultTableCellRenderer)tblProducts.getTableHeader().getDefaultRenderer())
            .setHorizontalAlignment(JLabel.CENTER);
        
        tblProducts.setRowHeight(25);
    }
    private void loadTableData() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblProducts.getModel();
    model.setRowCount(0);

    com.inventory.dao.ProductDAO dao = new com.inventory.dao.ProductDAO();
    java.util.List<com.inventory.model.Product> list = dao.getAllProducts();

    for (com.inventory.model.Product p : list) {
        model.addRow(new Object[]{
            p.getProductId(),
            p.getName(),
            p.getCategoryName(), // Populated by the JOIN in DAO
            p.getPrice(),
            p.getCurrentQuantity(),
            p.getMinThreshold(),
            p.getExpiryDate() != null ? p.getExpiryDate().toString() : "N/A"
        });
    }
    checkAlerts(list);
    
}
    
    private void clearFields() {
    txtName.setText("");
    txtPrice.setText("");
    txtQuantity.setText("");
    xtThreshold.setText("");
    dateExpiry.setDate(null);
    comboCategory.setSelectedIndex(0);
    btnSave.setEnabled(true);
    tblProducts.clearSelection();
}
    
    private void loadCategories() {
    comboCategory.removeAllItems(); // Clear default "Item 1, Item 2"
    com.inventory.dao.CategoryDAO catDAO = new com.inventory.dao.CategoryDAO();
    java.util.List<com.inventory.model.Category> list = catDAO.getAllCategories();
    
    for (com.inventory.model.Category cat : list) {
        comboCategory.addItem(cat.getCategoryName()); // Add names from DB
    }
}
    
    private void setupTableAlerts() {
    tblProducts.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            
            java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            // 1. Get data from the hidden/relevant columns (Qty, Threshold, Expiry)
            int qty = (int) table.getValueAt(row, 4);
            int threshold = (int) table.getValueAt(row, 5);
            String expiryStr = table.getValueAt(row, 6).toString();

            // 2. Logic for alerts
            boolean isLowStock = qty <= threshold;
            boolean isExpired = false;
            
            try {
                java.util.Date expiryDate = java.sql.Date.valueOf(expiryStr);
                isExpired = expiryDate.before(new java.util.Date());
            } catch (Exception e) { /* Handle N/A dates */ }

            // 3. Set Colors
            if (isSelected) {
                c.setBackground(table.getSelectionBackground());
            } else if (isExpired) {
                c.setBackground(new java.awt.Color(255, 204, 204)); // Light Red for Expired
                c.setForeground(java.awt.Color.RED);
            } else if (isLowStock) {
                c.setBackground(new java.awt.Color(255, 255, 204)); // Light Yellow for Low Stock
                c.setForeground(java.awt.Color.BLACK);
            } else {
                c.setBackground(java.awt.Color.WHITE);
                c.setForeground(java.awt.Color.BLACK);
            }

            return c;
        }
    });
}
    
    private void checkAlerts(List<com.inventory.model.Product> list) {
    StringBuilder lowStockItems = new StringBuilder("Low Stock Items:\n");
    StringBuilder expiredItems = new StringBuilder("Expired Items:\n");
    boolean foundLow = false;
    boolean foundExpired = false;

    java.util.Date today = new java.util.Date();

    for (com.inventory.model.Product p : list) {
        if (p.getCurrentQuantity() <= p.getMinThreshold()) {
            lowStockItems.append("- ").append(p.getName()).append("\n");
            foundLow = true;
        }
        if (p.getExpiryDate() != null && p.getExpiryDate().before(today)) {
            expiredItems.append("- ").append(p.getName()).append("\n");
            foundExpired = true;
        }
    }

    if (foundLow || foundExpired) {
        String message = (foundLow ? lowStockItems.toString() : "") + "\n" + (foundExpired ? expiredItems.toString() : "");
        javax.swing.JOptionPane.showMessageDialog(this, message, "Inventory Alerts", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboCategory;
    private com.toedter.calendar.JDateChooser dateExpiry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField xtThreshold;
    // End of variables declaration//GEN-END:variables
}
