/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.ui;


import javax.swing.table.DefaultTableCellRenderer;

import com.inventory.model.ProductSales;
import com.inventory.dao.AnalyticsDAO;
import javax.swing.JLabel;
import javax.swing.JProgressBar;


// 2. For the Database and List handling
import java.util.List;


// 3. For the UI Components (Table and Icons)
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author bhaskarjoshi
 */
public class SalesAnalysisPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form SalesAnalysisPanel
     */
    public SalesAnalysisPanel() {
        initComponents();
        
        setupTableUI();       // 2. Style the Table
    
        setScaledIcon(lblRevenueIcon, "/com/inventory/util/images/revenue.png");
        setScaledIcon(lblOrdersIcon, "/com/inventory/util/images/total_orders.png");
        setScaledIcon(lblCategoryIcon, "/com/inventory/util/images/best_selling.png");
        setScaledIcon(lblAvgValueIcon, "/com/inventory/util/images/avg_ordervalue.png");
        tblSalesInsights.getTableHeader().setFont(new java.awt.Font("STSong", java.awt.Font.BOLD, 18));
        tblSalesInsights.setRowHeight(30);
        tblSalesInsights.setFont(new java.awt.Font("STSong", java.awt.Font.PLAIN, 18));
        updateDashboardData(getSelectedDays());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        lblRevenueIcon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblBestCategory = new javax.swing.JLabel();
        lblCategoryIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblTotalOrders = new javax.swing.JLabel();
        lblOrdersIcon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblAvgOrderValue = new javax.swing.JLabel();
        lblAvgValueIcon = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboDuration = new javax.swing.JComboBox<>();
        btnRefresh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesInsights = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblHot1 = new javax.swing.JLabel();
        lblHot2 = new javax.swing.JLabel();
        lblHot3 = new javax.swing.JLabel();
        lblHot4 = new javax.swing.JLabel();
        lblHot5 = new javax.swing.JLabel();
        barHot1 = new javax.swing.JProgressBar();
        barHot2 = new javax.swing.JProgressBar();
        barHot3 = new javax.swing.JProgressBar();
        barHot4 = new javax.swing.JProgressBar();
        barHot5 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblCold1 = new javax.swing.JLabel();
        lblCold2 = new javax.swing.JLabel();
        lblCold3 = new javax.swing.JLabel();
        lblCold4 = new javax.swing.JLabel();
        lblCold5 = new javax.swing.JLabel();
        barCold1 = new javax.swing.JProgressBar();
        barCold2 = new javax.swing.JProgressBar();
        barCold3 = new javax.swing.JProgressBar();
        barCold4 = new javax.swing.JProgressBar();
        barCold5 = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("STSong", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOTAL REVENUE");

        lblTotalRevenue.setBackground(new java.awt.Color(0, 0, 0));
        lblTotalRevenue.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblTotalRevenue.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblRevenueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/util/images/revenue.png"))); // NOI18N
        lblRevenueIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRevenueIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRevenueIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        lblBestCategory.setBackground(new java.awt.Color(0, 0, 0));
        lblBestCategory.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblBestCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblBestCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCategoryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/util/images/best_selling.png"))); // NOI18N
        lblCategoryIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel6.setFont(new java.awt.Font("STSong", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BEST SELLING CATEGORY");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblCategoryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblBestCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategoryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblBestCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        lblTotalOrders.setBackground(new java.awt.Color(0, 0, 0));
        lblTotalOrders.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblTotalOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblOrdersIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/util/images/total_orders.png"))); // NOI18N
        lblOrdersIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel4.setFont(new java.awt.Font("STSong", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOTAL ORDERS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblOrdersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrdersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        lblAvgOrderValue.setBackground(new java.awt.Color(0, 0, 0));
        lblAvgOrderValue.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        lblAvgOrderValue.setForeground(new java.awt.Color(255, 255, 255));
        lblAvgOrderValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblAvgValueIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/inventory/util/images/avg_ordervalue.png"))); // NOI18N
        lblAvgValueIcon.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel8.setFont(new java.awt.Font("STSong", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("AVG ORDER VALUE");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblAvgValueIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(lblAvgOrderValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvgValueIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblAvgOrderValue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("STSong", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Analysis Period:");

        comboDuration.setBackground(new java.awt.Color(255, 255, 255));
        comboDuration.setFont(new java.awt.Font("STSong", 0, 18)); // NOI18N
        comboDuration.setForeground(new java.awt.Color(0, 0, 0));
        comboDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Last 7 Days", "Last 30 Days", "Last 6 Months", "Last Year" }));
        comboDuration.addActionListener(this::comboDurationActionPerformed);

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setForeground(new java.awt.Color(0, 0, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(comboDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRefresh)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        tblSalesInsights.setBackground(new java.awt.Color(255, 255, 255));
        tblSalesInsights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Category", "Qty Sold", "Total Revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSalesInsights);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(23, 23, 23))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("STSong", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("HOT PRODUCTS");

        lblHot1.setBackground(new java.awt.Color(0, 0, 0));
        lblHot1.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblHot1.setForeground(new java.awt.Color(0, 204, 0));

        lblHot2.setBackground(new java.awt.Color(0, 0, 0));
        lblHot2.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblHot2.setForeground(new java.awt.Color(0, 204, 0));

        lblHot3.setBackground(new java.awt.Color(0, 0, 0));
        lblHot3.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblHot3.setForeground(new java.awt.Color(0, 204, 0));

        lblHot4.setBackground(new java.awt.Color(0, 0, 0));
        lblHot4.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblHot4.setForeground(new java.awt.Color(0, 204, 0));

        lblHot5.setBackground(new java.awt.Color(0, 0, 0));
        lblHot5.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblHot5.setForeground(new java.awt.Color(0, 204, 0));

        barHot1.setBackground(new java.awt.Color(255, 87, 34));
        barHot1.setForeground(new java.awt.Color(0, 204, 0));

        barHot2.setBackground(new java.awt.Color(255, 87, 34));
        barHot2.setForeground(new java.awt.Color(0, 204, 0));

        barHot3.setBackground(new java.awt.Color(255, 87, 34));
        barHot3.setForeground(new java.awt.Color(0, 204, 0));

        barHot4.setBackground(new java.awt.Color(255, 87, 34));
        barHot4.setForeground(new java.awt.Color(0, 204, 0));

        barHot5.setBackground(new java.awt.Color(255, 87, 34));
        barHot5.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHot1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(barHot1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHot2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(barHot2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHot3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(barHot3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHot4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(barHot4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHot5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(barHot5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHot1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHot1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHot2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHot2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHot3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHot3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHot4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHot4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHot5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barHot5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("STSong", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("COLD PRODUCTS");

        lblCold1.setBackground(new java.awt.Color(0, 0, 0));
        lblCold1.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblCold1.setForeground(new java.awt.Color(0, 204, 0));

        lblCold2.setBackground(new java.awt.Color(0, 0, 0));
        lblCold2.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblCold2.setForeground(new java.awt.Color(0, 204, 0));

        lblCold3.setBackground(new java.awt.Color(0, 0, 0));
        lblCold3.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblCold3.setForeground(new java.awt.Color(0, 204, 0));

        lblCold4.setBackground(new java.awt.Color(0, 0, 0));
        lblCold4.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblCold4.setForeground(new java.awt.Color(0, 204, 0));

        lblCold5.setBackground(new java.awt.Color(0, 0, 0));
        lblCold5.setFont(new java.awt.Font("STSong", 1, 20)); // NOI18N
        lblCold5.setForeground(new java.awt.Color(0, 204, 0));

        barCold1.setBackground(new java.awt.Color(33, 150, 243));
        barCold1.setForeground(new java.awt.Color(0, 204, 0));

        barCold2.setBackground(new java.awt.Color(33, 150, 243));
        barCold2.setForeground(new java.awt.Color(0, 204, 0));

        barCold3.setBackground(new java.awt.Color(33, 150, 243));
        barCold3.setForeground(new java.awt.Color(0, 204, 0));

        barCold4.setBackground(new java.awt.Color(33, 150, 243));
        barCold4.setForeground(new java.awt.Color(0, 204, 0));

        barCold5.setBackground(new java.awt.Color(33, 150, 243));
        barCold5.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCold1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(barCold1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCold2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(barCold2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCold3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(barCold3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCold4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(barCold4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblCold5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(barCold5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCold1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCold1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCold2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCold2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCold3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCold3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCold4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCold4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCold5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barCold5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        updateDashboardData(getSelectedDays());
    // You can also add a small popup or console log here
    System.out.println("Dashboard Refreshed!");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void comboDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDurationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboDurationActionPerformed
    private void setScaledIcon(javax.swing.JLabel label, String resourcePath) {
    try {
        // 1. Get image from your 'images' package
        ImageIcon icon = new ImageIcon(getClass().getResource(resourcePath));
        
        // 2. Scale to 50x50 (Standard Dashboard Size)
        Image img = icon.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        
        // 3. Update the label
        label.setIcon(new ImageIcon(img));
        label.setText(""); // Remove any placeholder text
    } catch (Exception e) {
        System.out.println("Icon not found: " + resourcePath);
    }
}
    
    private void updateDashboardData(int days) {
    try {
        // 1. Initialize your DAO
        AnalyticsDAO dao = new AnalyticsDAO();

        // 2. Fetch data from DB
        double revenue = dao.getTotalRevenue(days);
        int orders = dao.getTotalOrders(days);
        String bestCat = dao.getBestCategory(days);

        // 3. Update KPI Labels
        // Revenue: Formatted to 2 decimal places
        lblTotalRevenue.setText("₹" + String.format("%.2f", revenue));

        // Orders: Simple conversion to String
        lblTotalOrders.setText(String.valueOf(orders));

        // Best Category: Direct string display
        lblBestCategory.setText(bestCat != null ? bestCat : "N/A");

        // 4. Calculate and set Average Order Value (AOV)
        if (orders > 0) {
            double avg = revenue / orders;
            lblAvgOrderValue.setText("₹" + String.format("%.2f", avg));
        } else {
            lblAvgOrderValue.setText("$0.00");
        }

        // 5. Refresh the Table Data
        updateSalesTable(days);

    } catch (Exception e) {
        System.out.println("Error updating dashboard: " + e.getMessage());
        e.printStackTrace();
    }
    updateProductRankings(days);
}
    
    private int getSelectedDays() {
    String selected = comboDuration.getSelectedItem().toString();
    switch (selected) {
        case "Last 7 Days": return 7;
        case "Last 30 Days": return 30;
        case "Last 6 Months": return 180;
        case "Last Year": return 365;
        default: return 30;
    }
}
    
    private void updateSalesTable(int days) {
    DefaultTableModel model = (DefaultTableModel) tblSalesInsights.getModel();
    model.setRowCount(0); 

    AnalyticsDAO dao = new AnalyticsDAO();
    List<ProductSales> list = dao.getProductSalesRanking(days, false);

    for (ProductSales ps : list) {
        Object[] row = {
            ps.getProductName(),
            ps.getCategoryName(), // CHANGED: Now using the real category name!
            ps.getQuantitySold(),
            "₹" + String.format("%.2f", ps.getRevenueGenerated())
        };
        model.addRow(row);
    }
}
    
    private void setupTableUI() {
    // 1. Get the header object from your Sales JTable
    javax.swing.table.JTableHeader header = tblSalesInsights.getTableHeader();

    // 2. Set the font to STSong, Bold, Size 18 (Matching User Management)
    header.setFont(new java.awt.Font("STSong", java.awt.Font.BOLD, 18));

    // 3. Set the text color to Black
    header.setForeground(java.awt.Color.BLACK);

    // 4. Increase header height for the 18pt font
    header.setPreferredSize(new java.awt.Dimension(header.getWidth(), 35));

    // 5. Center Alignment Logic for Rows
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    
    for (int i = 0; i < tblSalesInsights.getColumnCount(); i++) {
        tblSalesInsights.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    }

    // 6. Center Alignment Logic for Header Text
    ((DefaultTableCellRenderer)tblSalesInsights.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.JLabel.CENTER);
    
    // 7. Set Row Height (Using 30 or 35 for better readability of sales numbers)
    tblSalesInsights.setRowHeight(30); 
}
    
private void updateProductRankings(int days) {
    AnalyticsDAO dao = new AnalyticsDAO();
    int maxQty = 1; 

    // --- 1. HOT PRODUCTS (Top 5) ---
    List<ProductSales> hotList = dao.getProductSalesRanking(days, false);
    JLabel[] hotLabels = {lblHot1, lblHot2, lblHot3, lblHot4, lblHot5};
    JProgressBar[] hotBars = {barHot1, barHot2, barHot3, barHot4, barHot5};

    if (!hotList.isEmpty()) {
        maxQty = hotList.get(0).getQuantitySold(); 
        
        for (int i = 0; i < hotLabels.length; i++) {
            if (i < hotList.size()) {
                ProductSales ps = hotList.get(i);
                hotLabels[i].setText(ps.getProductName() + " [" + ps.getCategoryName() + "]");
                
                // FORCE UI to allow custom colors
                hotBars[i].setUI(new javax.swing.plaf.basic.BasicProgressBarUI());
                
                // COLORS: Foreground is Green, Background is Orange
                hotBars[i].setForeground(new java.awt.Color(0, 204, 0)); // Your Green
                hotBars[i].setBackground(new java.awt.Color(255, 87, 34)); // Hot Orange
                
                hotBars[i].setMaximum(maxQty);
                hotBars[i].setValue(ps.getQuantitySold());
                hotBars[i].setStringPainted(true);
                hotBars[i].setString(ps.getQuantitySold() + " sold");
                
                // SIZE: Force 30px height
                java.awt.Dimension bSize = new java.awt.Dimension(245, 30);
                hotBars[i].setPreferredSize(bSize);
                hotBars[i].setMinimumSize(bSize);
                
                hotBars[i].setVisible(true);
                hotBars[i].revalidate();
            } else {
                hotLabels[i].setText("");
                hotBars[i].setVisible(false);
            }
        }
    }

    // --- 2. COLD PRODUCTS (Least 5) ---
    List<ProductSales> coldList = dao.getProductSalesRanking(days, true);
    JLabel[] coldLabels = {lblCold1, lblCold2, lblCold3, lblCold4, lblCold5};
    JProgressBar[] coldBars = {barCold1, barCold2, barCold3, barCold4, barCold5};

    for (int i = 0; i < coldLabels.length; i++) {
        if (i < coldList.size()) {
            ProductSales ps = coldList.get(i);
            coldLabels[i].setText(ps.getProductName() + " [" + ps.getCategoryName() + "]");
            
            // FORCE UI to allow custom colors
            coldBars[i].setUI(new javax.swing.plaf.basic.BasicProgressBarUI());
            
            // COLORS: Foreground is Green, Background is Blue
            coldBars[i].setForeground(new java.awt.Color(0, 204, 0)); // Your Green
            coldBars[i].setBackground(new java.awt.Color(33, 150, 243)); // Cold Blue
            
            coldBars[i].setMaximum(maxQty); 
            coldBars[i].setValue(ps.getQuantitySold());
            coldBars[i].setStringPainted(true);
            coldBars[i].setString(ps.getQuantitySold() + " sold");
            
            // SIZE: Force 30px height
            java.awt.Dimension bSize = new java.awt.Dimension(245, 30);
            coldBars[i].setPreferredSize(bSize);
            coldBars[i].setMinimumSize(bSize);
            
            coldBars[i].setVisible(true);
            coldBars[i].revalidate();
        } else {
            coldLabels[i].setText("");
            coldBars[i].setVisible(false);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCold1;
    private javax.swing.JProgressBar barCold2;
    private javax.swing.JProgressBar barCold3;
    private javax.swing.JProgressBar barCold4;
    private javax.swing.JProgressBar barCold5;
    private javax.swing.JProgressBar barHot1;
    private javax.swing.JProgressBar barHot2;
    private javax.swing.JProgressBar barHot3;
    private javax.swing.JProgressBar barHot4;
    private javax.swing.JProgressBar barHot5;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> comboDuration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvgOrderValue;
    private javax.swing.JLabel lblAvgValueIcon;
    private javax.swing.JLabel lblBestCategory;
    private javax.swing.JLabel lblCategoryIcon;
    private javax.swing.JLabel lblCold1;
    private javax.swing.JLabel lblCold2;
    private javax.swing.JLabel lblCold3;
    private javax.swing.JLabel lblCold4;
    private javax.swing.JLabel lblCold5;
    private javax.swing.JLabel lblHot1;
    private javax.swing.JLabel lblHot2;
    private javax.swing.JLabel lblHot3;
    private javax.swing.JLabel lblHot4;
    private javax.swing.JLabel lblHot5;
    private javax.swing.JLabel lblOrdersIcon;
    private javax.swing.JLabel lblRevenueIcon;
    private javax.swing.JLabel lblTotalOrders;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tblSalesInsights;
    // End of variables declaration//GEN-END:variables
}
