/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.inventory.ui;

import com.inventory.dao.OrderDAO;
import com.inventory.model.Order;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhaskarjoshi
 */
public class ViewOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewOrderPanel
     */
    public ViewOrderPanel() {
        initComponents();
        loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrderHistory = new javax.swing.JTable();
        btnViewPDF = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setPreferredSize(null);
        setLayout(new java.awt.BorderLayout());

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile Number", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(500, 0));

        tblOrderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Name", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblOrderHistory);

        btnViewPDF.setText("View");
        btnViewPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewPDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnViewPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnViewPDF)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
       int row = tblCustomer.getSelectedRow();
    if (row != -1) {
        try {
            // Ensure column 0 is your 'Customer ID'
            Object idObj = tblCustomer.getValueAt(row, 0);
            if (idObj != null) {
                int customerId = Integer.parseInt(idObj.toString());
                System.out.println("Loading orders for Customer ID: " + customerId); // Debugging
                loadOrderHistory(customerId); 
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnViewPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPDFMouseClicked
        // TODO add your handling code here:
        // 1. Get the selected row from the Order History table
    int index = tblOrderHistory.getSelectedRow();
    
    // 2. Check if a row is actually selected
    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an order from the table first!");
        return;
    }
    
    // 3. Get the Order ID from the first column (Index 0)
    int orderId = Integer.parseInt(tblOrderHistory.getValueAt(index, 0).toString());
    
    // 4. Call your existing generatePDF method
    generatePDF(orderId);
    }//GEN-LAST:event_btnViewPDFMouseClicked

    
    private void generatePDF(int orderId) {
    try {
        String path = System.getProperty("user.home") + "/Documents/Order_" + orderId + ".pdf";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream(path));
        doc.open();
        
        doc.add(new com.itextpdf.text.Paragraph("INVENTORY MANAGEMENT SYSTEM - RECEIPT"));
        doc.add(new com.itextpdf.text.Paragraph("Order ID: " + orderId));
        doc.add(new com.itextpdf.text.Paragraph("--------------------------------------------------\n\n"));
        
        // Create Table for PDF
        com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(4);
        table.addCell("Product Name");
        table.addCell("Quantity");
        table.addCell("Price");
        table.addCell("Subtotal");

        // Fetch items from 'order_details' table in DB
        try (java.sql.Connection con = com.inventory.util.DBConnection.getConnection();
             java.sql.PreparedStatement ps = con.prepareStatement(
                 "SELECT p.name, od.quantity, od.price, od.subtotal " +
                 "FROM order_details od JOIN products p ON od.product_id = p.product_id " +
                 "WHERE od.order_id = ?")) {
            
            ps.setInt(1, orderId);
            java.sql.ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                table.addCell(rs.getString("name"));
                table.addCell(rs.getString("quantity"));
                table.addCell(rs.getString("price"));
                table.addCell(rs.getString("subtotal"));
            }
        }

        doc.add(table);
        doc.close();
        
        // Open the PDF on your Mac
        java.awt.Desktop.getDesktop().open(new java.io.File(path));
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    
    private void loadCustomers() {
    DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();
    model.setRowCount(0); // Clear existing rows
    
    try {
        // Reuse your existing CustomerDAO
        com.inventory.dao.CustomerDAO custDao = new com.inventory.dao.CustomerDAO();
        java.util.List<com.inventory.model.Customer> list = custDao.getAllCustomers();
        
        for (com.inventory.model.Customer c : list) {
            model.addRow(new Object[]{
                c.getCustomerId(), 
                c.getName(), 
                c.getMobile(),
                c.getEmail()
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
    }
}
    
    private void loadOrderHistory(int customerId) {
    DefaultTableModel model = (DefaultTableModel) tblOrderHistory.getModel();
    model.setRowCount(0); // Clear previous results
    
    com.inventory.dao.OrderDAO orderDao = new com.inventory.dao.OrderDAO();
    java.util.List<com.inventory.model.Order> list = orderDao.getOrdersByCustomer(customerId);
    
    if (list.isEmpty()) {
        System.out.println("No orders found in database for ID: " + customerId);
    } else {
        for (com.inventory.model.Order o : list) {
            model.addRow(new Object[]{
                o.getOrderId(), 
                o.getOrderDate(), 
                o.getTotalAmount()
            });
        }
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblOrderHistory;
    // End of variables declaration//GEN-END:variables
}
